databaseChangeLog:
  - changeSet:
      id: 4
      author: sitmun
      context: prod
      dbms: postgresql
      changes:
        - loadData:
            encoding: UTF-8
            file: 04_initial_data_prod/stm_user.csv
            relativeToChangelogFile: true
            tableName: STM_USER
            usePreparedStatements: false
            quotchar: '"'
            columns:
              - column:
                  name: USE_ID
                  type: NUMERIC
              - column:
                  name: USE_USER
                  type: STRING
              - column:
                  name: USE_PWD
                  type: STRING
              - column:
                  name: USE_NAME
                  type: STRING
              - column:
                  name: USE_SURNAME
                  type: STRING
              - column:
                  name: USE_ADM
                  type: BOOLEAN
              - column:
                  name: USE_BLOCKED
                  type: BOOLEAN
              - column:
                  name: USE_GENERIC
                  type: BOOLEAN
              - column:
                  name: USE_CREATED
                  type: DATETIME