databaseChangeLog:
  - changeSet:
      id: 8
      author: sitmun
      changes:
        - addColumn:
            tableName: STM_TERRITORY
            columns:
              - column:
                  name: TER_DESCRIPTION
                  type: varchar(4000)
                  remarks: Territory description
                  constraints:
                    nullable: true 