--liquibase formatted sql
--changeset sitmun:8 dbms:postgresql

ALTER TABLE STM_SERVICE ALTER COLUMN SER_ABSTRACT TYPE VARCHAR(4000);
ALTER TABLE STM_TRANSLATION ALTER COLUMN TRA_NAME TYPE VARCHAR(4000);

--changeset sitmun:8 dbms:oracle

ALTER TABLE STM_SERVICE MODIFY SER_ABSTRACT VARCHAR2(4000 CHAR);
ALTER TABLE STM_TRANSLATION MODIFY TRA_NAME VARCHAR2(4000 CHAR);

--changeset sitmun:8 dbms:h2

ALTER TABLE STM_SERVICE ALTER COLUMN SER_ABSTRACT VARCHAR2(4000);
ALTER TABLE STM_TRANSLATION ALTER COLUMN TRA_NAME VARCHAR2(4000);
