databaseChangeLog:
  - changeSet:
      id: 12
      author: sitmun
      context: dev,prod
      changes:
        - delete:
            tableName: STM_TRANSLATION
            where: 1=1
        - loadData:
            tableName: STM_TRANSLATION
            file: 12_translations/stm_translation_es.csv
            relativeToChangelogFile: true
            separator: ","
            encoding: UTF-8
            columns:
              - column:
                  name: TRA_ID
                  type: NUMERIC
              - column:
                  name: TRA_ELEID
                  type: NUMERIC
              - column:
                  name: TRA_COLUMN
                  type: STRING
              - column:
                  name: TRA_LANID
                  type: NUMERIC
              - column:
                  name: TRA_NAME
                  type: STRING
        - loadData:
            tableName: STM_TRANSLATION
            file: 12_translations/stm_translation_fr.csv
            separator: ","
            relativeToChangelogFile: true
            encoding: UTF-8
            columns:
              - column:
                  name: TRA_ID
                  type: NUMERIC
              - column:
                  name: TRA_ELEID
                  type: NUMERIC
              - column:
                  name: TRA_COLUMN
                  type: STRING
              - column:
                  name: TRA_LANID
                  type: NUMERIC
              - column:
                  name: TRA_NAME
                  type: STRING
        - loadData:
            tableName: STM_TRANSLATION
            file: 12_translations/stm_translation_oc.csv
            separator: ","
            relativeToChangelogFile: true
            encoding: UTF-8
            columns:
              - column:
                  name: TRA_ID
                  type: NUMERIC
              - column:
                  name: TRA_ELEID
                  type: NUMERIC
              - column:
                  name: TRA_COLUMN
                  type: STRING
              - column:
                  name: TRA_LANID
                  type: NUMERIC
              - column:
                  name: TRA_NAME
                  type: STRING
        - loadData:
            tableName: STM_TRANSLATION
            file: 12_translations/stm_translation_ca.csv
            separator: ","
            relativeToChangelogFile: true
            encoding: UTF-8
            columns:
              - column:
                  name: TRA_ID
                  type: NUMERIC
              - column:
                  name: TRA_ELEID
                  type: NUMERIC
              - column:
                  name: TRA_COLUMN
                  type: STRING
              - column:
                  name: TRA_LANID
                  type: NUMERIC
              - column:
                  name: TRA_NAME
                  type: STRING 