--liquibase formatted sql
--changeset sitmun:19 dbms:h2

-- Add APP_PRIVATE column to STM_APP table for H2
ALTER TABLE STM_APP ADD COLUMN APP_PRIVATE BOOLEAN DEFAULT FALSE NOT NULL;

-- Create STM_TOKEN_USER table for H2
CREATE TABLE STM_TOKEN_USER
(
  USER_TOKEN_ID INTEGER NOT NULL,
  USER_MAIL     VARCHAR2(50) NOT NULL,
  TOKEN_ID      VARCHAR2(150) NOT NULL,
  EXPIRE_AT     TIMESTAMP(6)
);

ALTER TABLE STM_TOKEN_USER
  ADD CONSTRAINT STM_TUS_PK PRIMARY KEY (USER_TOKEN_ID);

ALTER TABLE STM_TOKEN_USER
  ADD CONSTRAINT STM_TUS_UK UNIQUE (USER_MAIL, TOKEN_ID);

--changeset sitmun:19 dbms:oracle

-- Add APP_PRIVATE column to STM_APP table for Oracle
ALTER TABLE STM_APP ADD APP_PRIVATE NUMBER(1, 0) DEFAULT 0 NOT NULL;

-- Create STM_TOKEN_USER table for Oracle
CREATE TABLE STM_TOKEN_USER
(
  USER_TOKEN_ID NUMBER(10, 0) NOT NULL,
  USER_MAIL     VARCHAR2(50 CHAR) NOT NULL,
  TOKEN_ID      VARCHAR2(150 CHAR) NOT NULL,
  EXPIRE_AT     TIMESTAMP(6),
  PRIMARY KEY (USER_TOKEN_ID)
);

ALTER TABLE STM_TOKEN_USER
  ADD CONSTRAINT STM_TUS_UK UNIQUE (USER_MAIL, TOKEN_ID);

--changeset sitmun:19 dbms:postgresql

-- Add APP_PRIVATE column to STM_APP table for PostgreSQL
ALTER TABLE STM_APP ADD COLUMN APP_PRIVATE BOOLEAN DEFAULT FALSE NOT NULL;

-- Create STM_TOKEN_USER table for PostgreSQL
CREATE TABLE STM_TOKEN_USER
(
  USER_TOKEN_ID INT4 NOT NULL,
  USER_MAIL     VARCHAR(50) NOT NULL,
  TOKEN_ID      VARCHAR(150) NOT NULL,
  EXPIRE_AT     TIMESTAMP(6),
  PRIMARY KEY (USER_TOKEN_ID)
);

ALTER TABLE STM_TOKEN_USER
  ADD CONSTRAINT STM_TUS_UK UNIQUE (USER_MAIL, TOKEN_ID); 