--liquibase formatted sql
--changeset sitmun:27-1 context:dev,prod

-- Revert SILME-specific UI control names to standard SITNA names
UPDATE STM_TSK_UI SET TUI_NAME = 'sitna.basemapSelector' WHERE TUI_ID = 2;
UPDATE STM_TSK_UI SET TUI_NAME = 'sitna.drawMeasureModify' WHERE TUI_ID = 7;
UPDATE STM_TSK_UI SET TUI_NAME = 'sitna.featureInfo' WHERE TUI_ID = 8;
UPDATE STM_TSK_UI SET TUI_NAME = 'sitna.layerCatalog' WHERE TUI_ID = 11;
UPDATE STM_TSK_UI SET TUI_NAME = 'sitna.popup' WHERE TUI_ID = 19;
UPDATE STM_TSK_UI SET TUI_NAME = 'sitna.search' WHERE TUI_ID = 24;
UPDATE STM_TSK_UI SET TUI_NAME = 'sitna.streetView' WHERE TUI_ID = 26;
UPDATE STM_TSK_UI SET TUI_NAME = 'sitna.workLayerManager' WHERE TUI_ID = 31;

-- Merge duplicate controls to canonical task IDs
-- layerCatalog: 11 -> 35
UPDATE STM_AVAIL_TSK SET ATS_TASKID = 35 WHERE ATS_TASKID = 11;
UPDATE STM_ROL_TSK SET RTS_TASKID = 35 WHERE RTS_TASKID = 11;
UPDATE STM_TREE_NOD SET TNO_TASKID = 35 WHERE TNO_TASKID = 11;
UPDATE STM_TASKREL SET TAR_TASKID = 35 WHERE TAR_TASKID = 11;
UPDATE STM_TASKREL SET TAR_TASKRELID = 35 WHERE TAR_TASKRELID = 11;
UPDATE STM_LOG SET LOG_TASKID = 35 WHERE LOG_TASKID = 11;

-- workLayerManager: 31 -> 36
UPDATE STM_AVAIL_TSK SET ATS_TASKID = 36 WHERE ATS_TASKID = 31;
UPDATE STM_ROL_TSK SET RTS_TASKID = 36 WHERE RTS_TASKID = 31;
UPDATE STM_TREE_NOD SET TNO_TASKID = 36 WHERE TNO_TASKID = 31;
UPDATE STM_TASKREL SET TAR_TASKID = 36 WHERE TAR_TASKID = 31;
UPDATE STM_TASKREL SET TAR_TASKRELID = 36 WHERE TAR_TASKRELID = 31;
UPDATE STM_LOG SET LOG_TASKID = 36 WHERE LOG_TASKID = 31;

-- basemapSelector SILME: 34 -> 2
UPDATE STM_AVAIL_TSK SET ATS_TASKID = 2 WHERE ATS_TASKID = 34;
UPDATE STM_ROL_TSK SET RTS_TASKID = 2 WHERE RTS_TASKID = 34;
UPDATE STM_TREE_NOD SET TNO_TASKID = 2 WHERE TNO_TASKID = 34;
UPDATE STM_TASKREL SET TAR_TASKID = 2 WHERE TAR_TASKID = 34;
UPDATE STM_TASKREL SET TAR_TASKRELID = 2 WHERE TAR_TASKRELID = 34;
UPDATE STM_LOG SET LOG_TASKID = 2 WHERE LOG_TASKID = 34;

-- Remove unsupported controls
DELETE FROM STM_AVAIL_TSK WHERE ATS_TASKID IN (28, 32, 33);
DELETE FROM STM_ROL_TSK WHERE RTS_TASKID IN (28, 32, 33);
UPDATE STM_TREE_NOD SET TNO_TASKID = NULL WHERE TNO_TASKID IN (28, 32, 33);
DELETE FROM STM_TASKREL WHERE TAR_TASKID IN (28, 32, 33) OR TAR_TASKRELID IN (28, 32, 33);
UPDATE STM_LOG SET LOG_TASKID = NULL WHERE LOG_TASKID IN (28, 32, 33);

-- Remove duplicate and unsupported tasks
DELETE FROM STM_TASK WHERE TAS_ID IN (11, 31, 34, 28, 32, 33);

-- Remove duplicate and unsupported UI controls
DELETE FROM STM_TSK_UI WHERE TUI_ID IN (11, 31, 34, 28, 32, 33);

-- Update sequences after cleanup
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(TAS_ID), 0) + 1 FROM STM_TASK) WHERE SEQ_NAME = 'TAS_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(TUI_ID), 0) + 1 FROM STM_TSK_UI) WHERE SEQ_NAME = 'TUI_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(ATS_ID), 0) + 1 FROM STM_AVAIL_TSK) WHERE SEQ_NAME = 'ATS_ID';
