--liquibase formatted sql
--changeset sitmun:29-1 context:dev,prod
--
-- Align task names with backend-core seed data
UPDATE STM_TASK SET TAS_NAME = 'Map Attribution' WHERE TAS_ID = 1;
UPDATE STM_TASK SET TAS_NAME = 'Basemap Selector' WHERE TAS_ID = 2;
UPDATE STM_TASK SET TAS_NAME = 'Map Click' WHERE TAS_ID = 3;
UPDATE STM_TASK SET TAS_NAME = 'Coordinates Display' WHERE TAS_ID = 4;
UPDATE STM_TASK SET TAS_NAME = 'Data Loader' WHERE TAS_ID = 5;
UPDATE STM_TASK SET TAS_NAME = 'Download Data' WHERE TAS_ID = 6;
UPDATE STM_TASK SET TAS_NAME = 'Draw, Measure and Modify' WHERE TAS_ID = 7;
UPDATE STM_TASK SET TAS_NAME = 'Feature Information' WHERE TAS_ID = 8;
UPDATE STM_TASK SET TAS_NAME = 'Full Screen Mode' WHERE TAS_ID = 9;
UPDATE STM_TASK SET TAS_NAME = 'Geolocation and GPS Tracking' WHERE TAS_ID = 10;
UPDATE STM_TASK SET TAS_NAME = 'Layer Catalog' WHERE TAS_ID = 11;
UPDATE STM_TASK SET TAS_NAME = 'Map Legend' WHERE TAS_ID = 12;
UPDATE STM_TASK SET TAS_NAME = 'Loading Indicator' WHERE TAS_ID = 13;
UPDATE STM_TASK SET TAS_NAME = 'Measure Distance and Area' WHERE TAS_ID = 14;
UPDATE STM_TASK SET TAS_NAME = 'Multi Feature Information' WHERE TAS_ID = 15;
UPDATE STM_TASK SET TAS_NAME = 'Navigation Bar' WHERE TAS_ID = 16;
UPDATE STM_TASK SET TAS_NAME = 'Offline Map Maker (disabled by default in viewer)' WHERE TAS_ID = 17;
UPDATE STM_TASK SET TAS_NAME = 'Overview Map' WHERE TAS_ID = 18;
UPDATE STM_TASK SET TAS_NAME = 'Popup Window' WHERE TAS_ID = 19;
UPDATE STM_TASK SET TAS_NAME = 'Print Map' WHERE TAS_ID = 20;
UPDATE STM_TASK SET TAS_NAME = 'Scale Display' WHERE TAS_ID = 21;
UPDATE STM_TASK SET TAS_NAME = 'Scale Bar' WHERE TAS_ID = 22;
UPDATE STM_TASK SET TAS_NAME = 'Scale Selector' WHERE TAS_ID = 23;
UPDATE STM_TASK SET TAS_NAME = 'Search' WHERE TAS_ID = 24;
UPDATE STM_TASK SET TAS_NAME = 'Share Map' WHERE TAS_ID = 25;
UPDATE STM_TASK SET TAS_NAME = 'Street View' WHERE TAS_ID = 26;
UPDATE STM_TASK SET TAS_NAME = '3D View' WHERE TAS_ID = 27;
UPDATE STM_TASK SET TAS_NAME = 'WFS Feature Editor (disabled by default in viewer)' WHERE TAS_ID = 29;
UPDATE STM_TASK SET TAS_NAME = 'WFS Layer Query' WHERE TAS_ID = 30;
UPDATE STM_TASK SET TAS_NAME = 'Work Layer Manager' WHERE TAS_ID = 31;
UPDATE STM_TASK SET TAS_NAME = 'Events' WHERE TAS_ID = 35;
UPDATE STM_TASK SET TAS_NAME = 'Timetable' WHERE TAS_ID = 36;
