-- Comprobaciones post-migración: recuentos y FK huérfanas (Oracle).
-- Por qué: detectar filas no migradas, filtros EXISTS demasiado estrictos y referencias
-- rotas antes del COMMIT.
-- Esperad origen ≈ destino para las entidades migradas y 0 filas en las consultas de huérfanos.

COLUMN entity FORMAT A24
COLUMN src_cnt FORMAT 9999999
COLUMN tgt_cnt FORMAT 9999999

PROMPT === Recuentos origen vs destino ===
-- delta != 0 puede ser esperable si EXISTS ha omitido filas (p. ej. capas sin servicio).
SELECT entity, src_cnt, tgt_cnt, tgt_cnt - src_cnt AS delta
  FROM (
    SELECT 'STM_CONNECT' entity,
           (SELECT COUNT(*) FROM SITMUN2.STM_CONEXION) src_cnt,
           (SELECT COUNT(*) FROM STM_CONNECT) tgt_cnt FROM dual
    UNION ALL
    SELECT 'STM_USER',
           (SELECT COUNT(*) FROM SITMUN2.STM_USUARIO),
           (SELECT COUNT(*) FROM STM_USER) FROM dual
    UNION ALL
    SELECT 'STM_TERRITORY',
           (SELECT COUNT(*) FROM SITMUN2.STM_ETERRIT),
           (SELECT COUNT(*) FROM STM_TERRITORY) FROM dual
    UNION ALL
    SELECT 'STM_ROLE',
           (SELECT COUNT(*) FROM SITMUN2.STM_ROLES),
           (SELECT COUNT(*) FROM STM_ROLE) FROM dual
    UNION ALL
    SELECT 'STM_SERVICE',
           (SELECT COUNT(*) FROM SITMUN2.STM_SERVICIO),
           (SELECT COUNT(*) FROM STM_SERVICE) FROM dual
    UNION ALL
    SELECT 'STM_GEOINFO',
           (SELECT COUNT(*) FROM SITMUN2.STM_CARTO),
           (SELECT COUNT(*) FROM STM_GEOINFO) FROM dual
    UNION ALL
    SELECT 'STM_TSK_TYP',
           (SELECT COUNT(*) FROM SITMUN2.STM_TIPOTAREA),
           (SELECT COUNT(*) FROM STM_TSK_TYP) FROM dual
    UNION ALL
    SELECT 'STM_TASK',
           (SELECT COUNT(*) FROM SITMUN2.STM_TAREA),
           (SELECT COUNT(*) FROM STM_TASK) FROM dual
    UNION ALL
    SELECT 'STM_TREE',
           (SELECT COUNT(*) FROM SITMUN2.STM_ARBOL),
           (SELECT COUNT(*) FROM STM_TREE) FROM dual
    UNION ALL
    SELECT 'STM_TREE_NOD',
           (SELECT COUNT(*) FROM SITMUN2.STM_ARBOLNOD),
           (SELECT COUNT(*) FROM STM_TREE_NOD) FROM dual
    UNION ALL
    SELECT 'STM_APP',
           (SELECT COUNT(*) FROM SITMUN2.STM_APPS),
           (SELECT COUNT(*) FROM STM_APP) FROM dual
    UNION ALL
    SELECT 'STM_USR_CONF',
           (SELECT COUNT(*) FROM SITMUN2.STM_USUCONF),
           (SELECT COUNT(*) FROM STM_USR_CONF) FROM dual
    UNION ALL
    SELECT 'STM_APP_ROL',
           (SELECT COUNT(*) FROM SITMUN2.STM_ROLES),
           (SELECT COUNT(*) FROM STM_APP_ROL) FROM dual
    UNION ALL
    SELECT 'STM_GRP_GI',
           (SELECT COUNT(*) FROM SITMUN2.STM_GRPCARTO),
           (SELECT COUNT(*) FROM STM_GRP_GI) FROM dual
    UNION ALL
    SELECT 'STM_GGI_GI',
           (SELECT COUNT(*) FROM SITMUN2.STM_GCACAR),
           (SELECT COUNT(*) FROM STM_GGI_GI) FROM dual
    UNION ALL
    SELECT 'STM_ROL_GGI',
           (SELECT COUNT(*) FROM SITMUN2.STM_ROLGCA),
           (SELECT COUNT(*) FROM STM_ROL_GGI) FROM dual
    UNION ALL
    SELECT 'STM_BACKGRD',
           (SELECT COUNT(*) FROM SITMUN2.STM_FONDO),
           (SELECT COUNT(*) FROM STM_BACKGRD) FROM dual
    UNION ALL
    SELECT 'STM_APP_BCKG',
           (SELECT COUNT(*) FROM SITMUN2.STM_APPFON),
           (SELECT COUNT(*) FROM STM_APP_BCKG) FROM dual
    UNION ALL
    SELECT 'STM_GTER_TYP',
           (SELECT COUNT(*) FROM SITMUN2.STM_TIPOGRP),
           (SELECT COUNT(*) FROM STM_GTER_TYP) FROM dual
    UNION ALL
    SELECT 'STM_GRP_TER',
           (SELECT COUNT(*) FROM SITMUN2.STM_GRPTER),
           (SELECT COUNT(*) FROM STM_GRP_TER) FROM dual
    UNION ALL
    SELECT 'STM_POST',
           (SELECT COUNT(*) FROM SITMUN2.STM_CARGO),
           (SELECT COUNT(*) FROM STM_POST) FROM dual
    UNION ALL
    SELECT 'STM_PAR_APP',
           (SELECT COUNT(*) FROM SITMUN2.STM_PARAMAPP),
           (SELECT COUNT(*) FROM STM_PAR_APP) FROM dual
  )
 ORDER BY entity;

PROMPT === FK huérfanas (esperad 0 filas en cada bloque) ===

PROMPT -- STM_TASK: tipo / conexión / servicio / grupo / UI / cartografía
SELECT tas.TAS_ID, 'TAS_TTASKID' AS fk
  FROM STM_TASK tas
 WHERE tas.TAS_TTASKID IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM STM_TSK_TYP t WHERE t.TTY_ID = tas.TAS_TTASKID)
UNION ALL
SELECT tas.TAS_ID, 'TAS_CONNID'
  FROM STM_TASK tas
 WHERE tas.TAS_CONNID IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM STM_CONNECT c WHERE c.CON_ID = tas.TAS_CONNID)
UNION ALL
SELECT tas.TAS_ID, 'TAS_SERID'
  FROM STM_TASK tas
 WHERE tas.TAS_SERID IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM STM_SERVICE s WHERE s.SER_ID = tas.TAS_SERID)
UNION ALL
SELECT tas.TAS_ID, 'TAS_GTASKID'
  FROM STM_TASK tas
 WHERE tas.TAS_GTASKID IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM STM_GRP_TSK g WHERE g.GTS_ID = tas.TAS_GTASKID)
UNION ALL
SELECT tas.TAS_ID, 'TAS_TUIID'
  FROM STM_TASK tas
 WHERE tas.TAS_TUIID IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM STM_TSK_UI u WHERE u.TUI_ID = tas.TAS_TUIID)
UNION ALL
SELECT tas.TAS_ID, 'TAS_GIID'
  FROM STM_TASK tas
 WHERE tas.TAS_GIID IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM STM_GEOINFO g WHERE g.GEO_ID = tas.TAS_GIID);

PROMPT -- STM_TREE_NOD
SELECT n.TNO_ID, 'TNO_TREEID' AS fk
  FROM STM_TREE_NOD n
 WHERE NOT EXISTS (SELECT 1 FROM STM_TREE t WHERE t.TRE_ID = n.TNO_TREEID)
UNION ALL
SELECT n.TNO_ID, 'TNO_GIID'
  FROM STM_TREE_NOD n
 WHERE n.TNO_GIID IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM STM_GEOINFO g WHERE g.GEO_ID = n.TNO_GIID)
UNION ALL
SELECT n.TNO_ID, 'TNO_PARENTID'
  FROM STM_TREE_NOD n
 WHERE n.TNO_PARENTID IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM STM_TREE_NOD p WHERE p.TNO_ID = n.TNO_PARENTID);

PROMPT -- STM_USR_CONF
SELECT u.UCO_ID, 'UCO_USERID' AS fk
  FROM STM_USR_CONF u
 WHERE NOT EXISTS (SELECT 1 FROM STM_USER usr WHERE usr.USE_ID = u.UCO_USERID)
UNION ALL
SELECT u.UCO_ID, 'UCO_TERID'
  FROM STM_USR_CONF u
 WHERE NOT EXISTS (SELECT 1 FROM STM_TERRITORY t WHERE t.TER_ID = u.UCO_TERID)
UNION ALL
SELECT u.UCO_ID, 'UCO_ROLEID'
  FROM STM_USR_CONF u
 WHERE NOT EXISTS (SELECT 1 FROM STM_ROLE r WHERE r.ROL_ID = u.UCO_ROLEID);

PROMPT -- STM_APP_ROL / STM_APP_TREE / STM_APP_BCKG / APP_GGIID
SELECT a.ARO_APPID AS id, 'ARO_APPID' AS fk
  FROM STM_APP_ROL a
 WHERE NOT EXISTS (SELECT 1 FROM STM_APP app WHERE app.APP_ID = a.ARO_APPID)
UNION ALL
SELECT a.ARO_ROLEID, 'ARO_ROLEID'
  FROM STM_APP_ROL a
 WHERE NOT EXISTS (SELECT 1 FROM STM_ROLE r WHERE r.ROL_ID = a.ARO_ROLEID)
UNION ALL
SELECT t.ATR_ID, 'ATR_APPID'
  FROM STM_APP_TREE t
 WHERE NOT EXISTS (SELECT 1 FROM STM_APP app WHERE app.APP_ID = t.ATR_APPID)
UNION ALL
SELECT t.ATR_ID, 'ATR_TREEID'
  FROM STM_APP_TREE t
 WHERE NOT EXISTS (SELECT 1 FROM STM_TREE tr WHERE tr.TRE_ID = t.ATR_TREEID)
UNION ALL
SELECT b.ABC_ID, 'ABC_APPID'
  FROM STM_APP_BCKG b
 WHERE NOT EXISTS (SELECT 1 FROM STM_APP app WHERE app.APP_ID = b.ABC_APPID)
UNION ALL
SELECT b.ABC_ID, 'ABC_BACKID'
  FROM STM_APP_BCKG b
 WHERE NOT EXISTS (SELECT 1 FROM STM_BACKGRD bg WHERE bg.BAC_ID = b.ABC_BACKID)
UNION ALL
SELECT app.APP_ID, 'APP_GGIID'
  FROM STM_APP app
 WHERE app.APP_GGIID IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM STM_GRP_GI g WHERE g.GGI_ID = app.APP_GGIID);

PROMPT -- STM_GRP_GI / STM_GGI_GI / STM_ROL_GGI / STM_BACKGRD
SELECT g.GGG_GGIID AS id, 'GGG_GGIID' AS fk
  FROM STM_GGI_GI g
 WHERE NOT EXISTS (SELECT 1 FROM STM_GRP_GI gg WHERE gg.GGI_ID = g.GGG_GGIID)
UNION ALL
SELECT g.GGG_GIID, 'GGG_GIID'
  FROM STM_GGI_GI g
 WHERE NOT EXISTS (SELECT 1 FROM STM_GEOINFO gi WHERE gi.GEO_ID = g.GGG_GIID)
UNION ALL
SELECT r.RGG_ROLEID, 'RGG_ROLEID'
  FROM STM_ROL_GGI r
 WHERE NOT EXISTS (SELECT 1 FROM STM_ROLE rol WHERE rol.ROL_ID = r.RGG_ROLEID)
UNION ALL
SELECT r.RGG_GGIID, 'RGG_GGIID'
  FROM STM_ROL_GGI r
 WHERE NOT EXISTS (SELECT 1 FROM STM_GRP_GI g WHERE g.GGI_ID = r.RGG_GGIID)
UNION ALL
SELECT b.BAC_ID, 'BAC_GGIID'
  FROM STM_BACKGRD b
 WHERE b.BAC_GGIID IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM STM_GRP_GI g WHERE g.GGI_ID = b.BAC_GGIID);

PROMPT -- Fondos con grupo que no es tipo F (esperad 0)
SELECT b.BAC_ID, g.GGI_ID, g.GGI_TYPE
  FROM STM_BACKGRD b
  JOIN STM_GRP_GI g ON g.GGI_ID = b.BAC_GGIID
 WHERE g.GGI_TYPE <> 'F';

PROMPT -- STM_GRP_TER / STM_POST / STM_PAR_APP / TER_GTYPID
SELECT g.GTE_TERID AS id, 'GTE_TERID' AS fk
  FROM STM_GRP_TER g
 WHERE NOT EXISTS (SELECT 1 FROM STM_TERRITORY t WHERE t.TER_ID = g.GTE_TERID)
UNION ALL
SELECT g.GTE_TERMID, 'GTE_TERMID'
  FROM STM_GRP_TER g
 WHERE NOT EXISTS (SELECT 1 FROM STM_TERRITORY t WHERE t.TER_ID = g.GTE_TERMID)
UNION ALL
SELECT p.POS_ID, 'POS_USERID'
  FROM STM_POST p
 WHERE NOT EXISTS (SELECT 1 FROM STM_USER u WHERE u.USE_ID = p.POS_USERID)
UNION ALL
SELECT p.POS_ID, 'POS_TERID'
  FROM STM_POST p
 WHERE NOT EXISTS (SELECT 1 FROM STM_TERRITORY t WHERE t.TER_ID = p.POS_TERID)
UNION ALL
SELECT a.PAP_ID, 'PAP_APPID'
  FROM STM_PAR_APP a
 WHERE a.PAP_APPID IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM STM_APP app WHERE app.APP_ID = a.PAP_APPID)
UNION ALL
SELECT t.TER_ID, 'TER_GTYPID'
  FROM STM_TERRITORY t
 WHERE t.TER_GTYPID IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM STM_GTER_TYP g WHERE g.GTT_ID = t.TER_GTYPID);

PROMPT === Muestras de forma TAS_PARAMS ===
-- Por qué: verificar a ojo que las consultas tienen "scope" y las básicas no.
SELECT tas.TAS_ID,
       tas.TAS_TTASKID,
       CASE
         WHEN tas.TAS_PARAMS IS NULL THEN 'NULL'
         WHEN DBMS_LOB.INSTR(tas.TAS_PARAMS, '"scope"') > 0 THEN 'con-scope'
         ELSE 'sin-scope'
       END AS pista_forma,
       DBMS_LOB.SUBSTR(tas.TAS_PARAMS, 200, 1) AS prefijo_params
  FROM STM_TASK tas
 WHERE tas.TAS_PARAMS IS NOT NULL
   AND ROWNUM <= 20
 ORDER BY tas.TAS_ID;

PROMPT === STM_SEQUENCE (claves migradas) ===
SELECT SEQ_NAME, SEQ_COUNT
  FROM STM_SEQUENCE
 WHERE SEQ_NAME IN (
         'APP_ID','USE_ID','TER_ID','ROL_ID','UCO_ID','CON_ID','SER_ID','PSE_ID',
         'GEO_ID','PGI_ID','PAP_ID','AGI_ID','ATS_ID','GTS_ID','GTT_ID','TTY_ID','TUI_ID',
         'TAS_ID','TRE_ID','TNO_ID','ATR_ID','GGI_ID','BAC_ID','ABC_ID','POS_ID'
       )
 ORDER BY SEQ_NAME;

PROMPT === post_checks terminado ===
