--liquibase formatted sql
--changeset sitmun:14 context:dev,prod

UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(TTY_ID), 0) + 1 FROM STM_TSK_TYP) WHERE SEQ_NAME = 'TTY_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(TET_ID), 0) + 1 FROM STM_TER_TYP) WHERE SEQ_NAME = 'TET_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(CON_ID), 0) + 1 FROM STM_CONNECT) WHERE SEQ_NAME = 'CON_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(GTT_ID), 0) + 1 FROM STM_GTER_TYP) WHERE SEQ_NAME = 'GTT_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(PGI_ID), 0) + 1 FROM STM_PAR_GI) WHERE SEQ_NAME = 'PGI_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(GTS_ID), 0) + 1 FROM STM_GRP_TSK) WHERE SEQ_NAME = 'GTS_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(TUI_ID), 0) + 1 FROM STM_TSK_UI) WHERE SEQ_NAME = 'TUI_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(COM_ID), 0) + 1 FROM STM_COMMENT) WHERE SEQ_NAME = 'COM_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(TER_ID), 0) + 1 FROM STM_TERRITORY) WHERE SEQ_NAME = 'THE_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LAN_ID), 0) + 1 FROM STM_LANGUAGE) WHERE SEQ_NAME = 'LAN_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(PGI_ID), 0) + 1 FROM STM_PAR_GI) WHERE SEQ_NAME = 'PTT_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(APP_ID), 0) + 1 FROM STM_APP) WHERE SEQ_NAME = 'APP_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(POS_ID), 0) + 1 FROM STM_POST) WHERE SEQ_NAME = 'POS_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(ROL_ID), 0) + 1 FROM STM_ROLE) WHERE SEQ_NAME = 'ROL_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(UCO_ID), 0) + 1 FROM STM_USR_CONF) WHERE SEQ_NAME = 'UCO_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(USE_ID), 0) + 1 FROM STM_USER) WHERE SEQ_NAME = 'USE_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(TER_ID), 0) + 1 FROM STM_TERRITORY) WHERE SEQ_NAME = 'TER_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(AGI_ID), 0) + 1 FROM STM_AVAIL_GI) WHERE SEQ_NAME = 'AGI_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(PSE_ID), 0) + 1 FROM STM_PAR_SER) WHERE SEQ_NAME = 'PSE_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(CNF_ID), 0) + 1 FROM STM_CONF) WHERE SEQ_NAME = 'CNF_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(PSG_ID), 0) + 1 FROM STM_PAR_SGI) WHERE SEQ_NAME = 'PSG_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(PAP_ID), 0) + 1 FROM STM_PAR_APP) WHERE SEQ_NAME = 'PAP_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(GGI_ID), 0) + 1 FROM STM_GRP_GI) WHERE SEQ_NAME = 'GGI_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(BAC_ID), 0) + 1 FROM STM_BACKGRD) WHERE SEQ_NAME = 'BAC_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(ABC_ID), 0) + 1 FROM STM_APP_BCKG) WHERE SEQ_NAME = 'ABC_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(TAS_ID), 0) + 1 FROM STM_TASK) WHERE SEQ_NAME = 'TAS_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(TRE_ID), 0) + 1 FROM STM_TREE) WHERE SEQ_NAME = 'TRE_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(COD_ID), 0) + 1 FROM STM_CODELIST) WHERE SEQ_NAME = 'COD_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(ATS_ID), 0) + 1 FROM STM_AVAIL_TSK) WHERE SEQ_NAME = 'ATS_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(GEO_ID), 0) + 1 FROM STM_GEOINFO) WHERE SEQ_NAME = 'GEO_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(TNO_ID), 0) + 1 FROM STM_TREE_NOD) WHERE SEQ_NAME = 'TNO_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(SGI_ID), 0) + 1 FROM STM_STY_GI) WHERE SEQ_NAME = 'SGI_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(SER_ID), 0) + 1 FROM STM_SERVICE) WHERE SEQ_NAME = 'SER_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(TRA_ID), 0) + 1 FROM STM_TRANSLATION) WHERE SEQ_NAME = 'TRA_ID'; 