--liquibase formatted sql
--changeset sitmun:17 dbms:postgresql

ALTER TABLE STM_APP ADD COLUMN APP_MAINTENANCE_INFORMATION VARCHAR(4000);
ALTER TABLE STM_APP ADD COLUMN APP_UNAVAILABLE BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE STM_APP ADD COLUMN APP_LAST_UPDATE TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE STM_APP ADD COLUMN APP_CREATORID INTEGER;

ALTER TABLE STM_APP
  ADD CONSTRAINT STM_APP_FK_USE FOREIGN KEY (APP_CREATORID) REFERENCES STM_USER (USE_ID) ON DELETE CASCADE;

--changeset sitmun:17 dbms:oracle

ALTER TABLE STM_APP ADD APP_MAINTENANCE_INFORMATION VARCHAR2(4000);
ALTER TABLE STM_APP ADD APP_UNAVAILABLE NUMBER(1) DEFAULT 0 NOT NULL;
ALTER TABLE STM_APP ADD APP_LAST_UPDATE TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL;
ALTER TABLE STM_APP ADD APP_CREATORID NUMBER(10);

ALTER TABLE STM_APP
  ADD CONSTRAINT STM_APP_FK_USE FOREIGN KEY (APP_CREATORID) REFERENCES STM_USER (USE_ID) ON DELETE CASCADE;

--changeset sitmun:17 dbms:h2

ALTER TABLE STM_APP ADD COLUMN APP_MAINTENANCE_INFORMATION VARCHAR(4000);
ALTER TABLE STM_APP ADD COLUMN APP_UNAVAILABLE BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE STM_APP ADD COLUMN APP_LAST_UPDATE TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE STM_APP ADD COLUMN APP_CREATORID INTEGER;

ALTER TABLE STM_APP
  ADD CONSTRAINT STM_APP_FK_USE FOREIGN KEY (APP_CREATORID) REFERENCES STM_USER (USE_ID) ON DELETE CASCADE;
