--liquibase formatted sql
--changeset sitmun:23 dbms:postgresql

DROP TABLE STM_TOKEN_USER;

CREATE TABLE STM_TOKEN_USER
(
  USER_TOKEN_ID INTEGER NOT NULL,
  USER_ID       INTEGER NOT NULL,
  CODE_OTP      VARCHAR(150) NOT NULL,
  EXPIRE_AT     TIMESTAMP(6),
  ATTEMPT_COUNTER INTEGER NOT NULL,
  ACTIVE BOOLEAN NOT NULL,
  PRIMARY KEY (USER_TOKEN_ID)
);

ALTER TABLE STM_TOKEN_USER
  ADD CONSTRAINT STM_TUS_UK UNIQUE (USER_ID);

ALTER TABLE STM_USER
  ADD COLUMN USE_LAST_PASSWORD_CHANGE TIMESTAMP(6);

--changeset sitmun:23 dbms:oracle

DROP TABLE STM_TOKEN_USER;

CREATE TABLE STM_TOKEN_USER
(
  USER_TOKEN_ID NUMBER(10, 0) NOT NULL,
  USER_ID       NUMBER(10, 0) NOT NULL,
  CODE_OTP      VARCHAR2(150) NOT NULL,
  EXPIRE_AT     TIMESTAMP(6),
  ATTEMPT_COUNTER NUMBER(10, 0) NOT NULL,
  ACTIVE BOOLEAN NOT NULL,
  PRIMARY KEY (USER_TOKEN_ID)
);

ALTER TABLE STM_TOKEN_USER
  ADD CONSTRAINT STM_TUS_UK UNIQUE (USER_ID);

ALTER TABLE STM_USER
  ADD USE_LAST_PASSWORD_CHANGE TIMESTAMP(6);


--changeset sitmun:23 dbms:h2

DROP TABLE STM_TOKEN_USER;

CREATE TABLE STM_TOKEN_USER
(
  USER_TOKEN_ID INTEGER NOT NULL,
  USER_ID       INTEGER NOT NULL,
  CODE_OTP      VARCHAR2(150) NOT NULL,
  EXPIRE_AT     TIMESTAMP(6),
  ATTEMPT_COUNTER INTEGER NOT NULL,
  ACTIVE BOOLEAN NOT NULL
);

ALTER TABLE STM_TOKEN_USER
  ADD CONSTRAINT STM_TUS_PK PRIMARY KEY (USER_TOKEN_ID);

ALTER TABLE STM_TOKEN_USER
  ADD CONSTRAINT STM_TUS_UK UNIQUE (USER_ID);

ALTER TABLE STM_USER
  ADD COLUMN USE_LAST_PASSWORD_CHANGE TIMESTAMP(6);

