--liquibase formatted sql

-- Collapsed greenfield seed (replaces earlier split MIA chrome seed drafts).
-- English keys; LTR_LANID = en (1). Values: ca=3, es=2, en=1, fr=5.

--changeset sitmun:65-seed-mia-chrome-no-data-h2 dbms:h2
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM STM_LITERAL_TRANSLATION WHERE LTR_LITERAL = 'No data'
INSERT INTO STM_LITERAL_TRANSLATION (LTR_ID, LTR_LITERAL, LTR_LANID)
SELECT COALESCE((SELECT MAX(LTR_ID) FROM STM_LITERAL_TRANSLATION), 0) + 1, 'No data', 1
FROM STM_LANGUAGE WHERE LAN_ID = 1;
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 3, 'Sense dades'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'No data';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 2, 'Sin datos'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'No data';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 1, 'No data'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'No data';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 5, 'Aucune donnee'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'No data';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTR_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION) WHERE SEQ_NAME = 'LTR_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTV_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION_VALUE) WHERE SEQ_NAME = 'LTV_ID';

--changeset sitmun:65-seed-mia-chrome-no-data-postgresql dbms:postgresql
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM STM_LITERAL_TRANSLATION WHERE LTR_LITERAL = 'No data'
INSERT INTO STM_LITERAL_TRANSLATION (LTR_ID, LTR_LITERAL, LTR_LANID)
SELECT COALESCE((SELECT MAX(LTR_ID) FROM STM_LITERAL_TRANSLATION), 0) + 1, 'No data', 1
FROM STM_LANGUAGE WHERE LAN_ID = 1;
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 3, 'Sense dades'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'No data';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 2, 'Sin datos'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'No data';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 1, 'No data'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'No data';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 5, 'Aucune donnee'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'No data';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTR_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION) WHERE SEQ_NAME = 'LTR_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTV_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION_VALUE) WHERE SEQ_NAME = 'LTV_ID';

--changeset sitmun:65-seed-mia-chrome-no-data-oracle dbms:oracle
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM STM_LITERAL_TRANSLATION WHERE LTR_LITERAL = 'No data'
INSERT INTO STM_LITERAL_TRANSLATION (LTR_ID, LTR_LITERAL, LTR_LANID)
SELECT COALESCE((SELECT MAX(LTR_ID) FROM STM_LITERAL_TRANSLATION), 0) + 1, 'No data', 1
FROM STM_LANGUAGE WHERE LAN_ID = 1;
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 3, 'Sense dades'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'No data';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 2, 'Sin datos'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'No data';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 1, 'No data'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'No data';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 5, 'Aucune donnee'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'No data';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTR_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION) WHERE SEQ_NAME = 'LTR_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTV_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION_VALUE) WHERE SEQ_NAME = 'LTV_ID';

--changeset sitmun:65-seed-mia-chrome-error-executing-task-h2 dbms:h2
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM STM_LITERAL_TRANSLATION WHERE LTR_LITERAL = 'Error executing task'
INSERT INTO STM_LITERAL_TRANSLATION (LTR_ID, LTR_LITERAL, LTR_LANID)
SELECT COALESCE((SELECT MAX(LTR_ID) FROM STM_LITERAL_TRANSLATION), 0) + 1, 'Error executing task', 1
FROM STM_LANGUAGE WHERE LAN_ID = 1;
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 3, 'Error executant la tasca'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Error executing task';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 2, 'Error ejecutando tarea'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Error executing task';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 1, 'Error executing task'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Error executing task';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 5, 'Erreur d execution de la tache'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Error executing task';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTR_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION) WHERE SEQ_NAME = 'LTR_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTV_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION_VALUE) WHERE SEQ_NAME = 'LTV_ID';

--changeset sitmun:65-seed-mia-chrome-error-executing-task-postgresql dbms:postgresql
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM STM_LITERAL_TRANSLATION WHERE LTR_LITERAL = 'Error executing task'
INSERT INTO STM_LITERAL_TRANSLATION (LTR_ID, LTR_LITERAL, LTR_LANID)
SELECT COALESCE((SELECT MAX(LTR_ID) FROM STM_LITERAL_TRANSLATION), 0) + 1, 'Error executing task', 1
FROM STM_LANGUAGE WHERE LAN_ID = 1;
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 3, 'Error executant la tasca'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Error executing task';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 2, 'Error ejecutando tarea'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Error executing task';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 1, 'Error executing task'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Error executing task';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 5, 'Erreur d execution de la tache'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Error executing task';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTR_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION) WHERE SEQ_NAME = 'LTR_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTV_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION_VALUE) WHERE SEQ_NAME = 'LTV_ID';

--changeset sitmun:65-seed-mia-chrome-error-executing-task-oracle dbms:oracle
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM STM_LITERAL_TRANSLATION WHERE LTR_LITERAL = 'Error executing task'
INSERT INTO STM_LITERAL_TRANSLATION (LTR_ID, LTR_LITERAL, LTR_LANID)
SELECT COALESCE((SELECT MAX(LTR_ID) FROM STM_LITERAL_TRANSLATION), 0) + 1, 'Error executing task', 1
FROM STM_LANGUAGE WHERE LAN_ID = 1;
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 3, 'Error executant la tasca'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Error executing task';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 2, 'Error ejecutando tarea'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Error executing task';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 1, 'Error executing task'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Error executing task';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 5, 'Erreur d execution de la tache'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Error executing task';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTR_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION) WHERE SEQ_NAME = 'LTR_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTV_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION_VALUE) WHERE SEQ_NAME = 'LTV_ID';

--changeset sitmun:65-seed-mia-chrome-query-h2 dbms:h2
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM STM_LITERAL_TRANSLATION WHERE LTR_LITERAL = 'Query'
INSERT INTO STM_LITERAL_TRANSLATION (LTR_ID, LTR_LITERAL, LTR_LANID)
SELECT COALESCE((SELECT MAX(LTR_ID) FROM STM_LITERAL_TRANSLATION), 0) + 1, 'Query', 1
FROM STM_LANGUAGE WHERE LAN_ID = 1;
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 3, 'Consulta'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Query';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 2, 'Consulta'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Query';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 1, 'Query'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Query';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 5, 'Requete'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Query';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTR_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION) WHERE SEQ_NAME = 'LTR_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTV_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION_VALUE) WHERE SEQ_NAME = 'LTV_ID';

--changeset sitmun:65-seed-mia-chrome-query-postgresql dbms:postgresql
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM STM_LITERAL_TRANSLATION WHERE LTR_LITERAL = 'Query'
INSERT INTO STM_LITERAL_TRANSLATION (LTR_ID, LTR_LITERAL, LTR_LANID)
SELECT COALESCE((SELECT MAX(LTR_ID) FROM STM_LITERAL_TRANSLATION), 0) + 1, 'Query', 1
FROM STM_LANGUAGE WHERE LAN_ID = 1;
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 3, 'Consulta'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Query';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 2, 'Consulta'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Query';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 1, 'Query'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Query';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 5, 'Requete'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Query';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTR_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION) WHERE SEQ_NAME = 'LTR_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTV_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION_VALUE) WHERE SEQ_NAME = 'LTV_ID';

--changeset sitmun:65-seed-mia-chrome-query-oracle dbms:oracle
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM STM_LITERAL_TRANSLATION WHERE LTR_LITERAL = 'Query'
INSERT INTO STM_LITERAL_TRANSLATION (LTR_ID, LTR_LITERAL, LTR_LANID)
SELECT COALESCE((SELECT MAX(LTR_ID) FROM STM_LITERAL_TRANSLATION), 0) + 1, 'Query', 1
FROM STM_LANGUAGE WHERE LAN_ID = 1;
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 3, 'Consulta'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Query';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 2, 'Consulta'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Query';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 1, 'Query'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Query';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 5, 'Requete'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Query';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTR_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION) WHERE SEQ_NAME = 'LTR_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTV_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION_VALUE) WHERE SEQ_NAME = 'LTV_ID';

--changeset sitmun:65-seed-mia-chrome-invalid-child-task-id-h2 dbms:h2
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM STM_LITERAL_TRANSLATION WHERE LTR_LITERAL = 'Invalid child task id'
INSERT INTO STM_LITERAL_TRANSLATION (LTR_ID, LTR_LITERAL, LTR_LANID)
SELECT COALESCE((SELECT MAX(LTR_ID) FROM STM_LITERAL_TRANSLATION), 0) + 1, 'Invalid child task id', 1
FROM STM_LANGUAGE WHERE LAN_ID = 1;
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 3, 'Identificador de tasca fill no valid'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Invalid child task id';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 2, 'Id de tarea hija no valido'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Invalid child task id';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 1, 'Invalid child task id'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Invalid child task id';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 5, 'Identifiant de tache enfant invalide'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Invalid child task id';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTR_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION) WHERE SEQ_NAME = 'LTR_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTV_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION_VALUE) WHERE SEQ_NAME = 'LTV_ID';

--changeset sitmun:65-seed-mia-chrome-invalid-child-task-id-postgresql dbms:postgresql
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM STM_LITERAL_TRANSLATION WHERE LTR_LITERAL = 'Invalid child task id'
INSERT INTO STM_LITERAL_TRANSLATION (LTR_ID, LTR_LITERAL, LTR_LANID)
SELECT COALESCE((SELECT MAX(LTR_ID) FROM STM_LITERAL_TRANSLATION), 0) + 1, 'Invalid child task id', 1
FROM STM_LANGUAGE WHERE LAN_ID = 1;
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 3, 'Identificador de tasca fill no valid'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Invalid child task id';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 2, 'Id de tarea hija no valido'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Invalid child task id';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 1, 'Invalid child task id'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Invalid child task id';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 5, 'Identifiant de tache enfant invalide'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Invalid child task id';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTR_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION) WHERE SEQ_NAME = 'LTR_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTV_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION_VALUE) WHERE SEQ_NAME = 'LTV_ID';

--changeset sitmun:65-seed-mia-chrome-invalid-child-task-id-oracle dbms:oracle
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM STM_LITERAL_TRANSLATION WHERE LTR_LITERAL = 'Invalid child task id'
INSERT INTO STM_LITERAL_TRANSLATION (LTR_ID, LTR_LITERAL, LTR_LANID)
SELECT COALESCE((SELECT MAX(LTR_ID) FROM STM_LITERAL_TRANSLATION), 0) + 1, 'Invalid child task id', 1
FROM STM_LANGUAGE WHERE LAN_ID = 1;
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 3, 'Identificador de tasca fill no valid'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Invalid child task id';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 2, 'Id de tarea hija no valido'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Invalid child task id';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 1, 'Invalid child task id'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Invalid child task id';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 5, 'Identifiant de tache enfant invalide'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Invalid child task id';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTR_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION) WHERE SEQ_NAME = 'LTR_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTV_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION_VALUE) WHERE SEQ_NAME = 'LTV_ID';

--changeset sitmun:65-seed-mia-chrome-task-not-executed-h2 dbms:h2
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM STM_LITERAL_TRANSLATION WHERE LTR_LITERAL = 'task not executed'
INSERT INTO STM_LITERAL_TRANSLATION (LTR_ID, LTR_LITERAL, LTR_LANID)
SELECT COALESCE((SELECT MAX(LTR_ID) FROM STM_LITERAL_TRANSLATION), 0) + 1, 'task not executed', 1
FROM STM_LANGUAGE WHERE LAN_ID = 1;
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 3, 'cal executar la tasca'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'task not executed';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 2, 'falta ejecutar tarea'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'task not executed';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 1, 'task not executed'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'task not executed';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 5, 'tache non executee'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'task not executed';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTR_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION) WHERE SEQ_NAME = 'LTR_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTV_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION_VALUE) WHERE SEQ_NAME = 'LTV_ID';

--changeset sitmun:65-seed-mia-chrome-task-not-executed-postgresql dbms:postgresql
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM STM_LITERAL_TRANSLATION WHERE LTR_LITERAL = 'task not executed'
INSERT INTO STM_LITERAL_TRANSLATION (LTR_ID, LTR_LITERAL, LTR_LANID)
SELECT COALESCE((SELECT MAX(LTR_ID) FROM STM_LITERAL_TRANSLATION), 0) + 1, 'task not executed', 1
FROM STM_LANGUAGE WHERE LAN_ID = 1;
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 3, 'cal executar la tasca'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'task not executed';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 2, 'falta ejecutar tarea'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'task not executed';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 1, 'task not executed'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'task not executed';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 5, 'tache non executee'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'task not executed';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTR_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION) WHERE SEQ_NAME = 'LTR_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTV_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION_VALUE) WHERE SEQ_NAME = 'LTV_ID';

--changeset sitmun:65-seed-mia-chrome-task-not-executed-oracle dbms:oracle
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM STM_LITERAL_TRANSLATION WHERE LTR_LITERAL = 'task not executed'
INSERT INTO STM_LITERAL_TRANSLATION (LTR_ID, LTR_LITERAL, LTR_LANID)
SELECT COALESCE((SELECT MAX(LTR_ID) FROM STM_LITERAL_TRANSLATION), 0) + 1, 'task not executed', 1
FROM STM_LANGUAGE WHERE LAN_ID = 1;
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 3, 'cal executar la tasca'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'task not executed';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 2, 'falta ejecutar tarea'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'task not executed';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 1, 'task not executed'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'task not executed';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 5, 'tache non executee'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'task not executed';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTR_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION) WHERE SEQ_NAME = 'LTR_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTV_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION_VALUE) WHERE SEQ_NAME = 'LTV_ID';

--changeset sitmun:65-seed-mia-chrome-binary-access-message-h2 dbms:h2
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM STM_LITERAL_TRANSLATION WHERE LTR_LITERAL = 'Binary content cannot be embedded: server authentication required'
INSERT INTO STM_LITERAL_TRANSLATION (LTR_ID, LTR_LITERAL, LTR_LANID)
SELECT COALESCE((SELECT MAX(LTR_ID) FROM STM_LITERAL_TRANSLATION), 0) + 1, 'Binary content cannot be embedded: server authentication required', 1
FROM STM_LANGUAGE WHERE LAN_ID = 1;
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 3, 'Contingut binari no incrustable: cal autenticacio de servidor'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Binary content cannot be embedded: server authentication required';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 2, 'Contenido binario no embebible: requiere autenticacion de servidor'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Binary content cannot be embedded: server authentication required';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 1, 'Binary content cannot be embedded: server authentication required'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Binary content cannot be embedded: server authentication required';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 5, 'Contenu binaire non integrable: authentification serveur requise'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Binary content cannot be embedded: server authentication required';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTR_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION) WHERE SEQ_NAME = 'LTR_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTV_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION_VALUE) WHERE SEQ_NAME = 'LTV_ID';

--changeset sitmun:65-seed-mia-chrome-binary-access-message-postgresql dbms:postgresql
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM STM_LITERAL_TRANSLATION WHERE LTR_LITERAL = 'Binary content cannot be embedded: server authentication required'
INSERT INTO STM_LITERAL_TRANSLATION (LTR_ID, LTR_LITERAL, LTR_LANID)
SELECT COALESCE((SELECT MAX(LTR_ID) FROM STM_LITERAL_TRANSLATION), 0) + 1, 'Binary content cannot be embedded: server authentication required', 1
FROM STM_LANGUAGE WHERE LAN_ID = 1;
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 3, 'Contingut binari no incrustable: cal autenticacio de servidor'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Binary content cannot be embedded: server authentication required';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 2, 'Contenido binario no embebible: requiere autenticacion de servidor'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Binary content cannot be embedded: server authentication required';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 1, 'Binary content cannot be embedded: server authentication required'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Binary content cannot be embedded: server authentication required';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 5, 'Contenu binaire non integrable: authentification serveur requise'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Binary content cannot be embedded: server authentication required';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTR_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION) WHERE SEQ_NAME = 'LTR_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTV_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION_VALUE) WHERE SEQ_NAME = 'LTV_ID';

--changeset sitmun:65-seed-mia-chrome-binary-access-message-oracle dbms:oracle
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM STM_LITERAL_TRANSLATION WHERE LTR_LITERAL = 'Binary content cannot be embedded: server authentication required'
INSERT INTO STM_LITERAL_TRANSLATION (LTR_ID, LTR_LITERAL, LTR_LANID)
SELECT COALESCE((SELECT MAX(LTR_ID) FROM STM_LITERAL_TRANSLATION), 0) + 1, 'Binary content cannot be embedded: server authentication required', 1
FROM STM_LANGUAGE WHERE LAN_ID = 1;
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 3, 'Contingut binari no incrustable: cal autenticacio de servidor'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Binary content cannot be embedded: server authentication required';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 2, 'Contenido binario no embebible: requiere autenticacion de servidor'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Binary content cannot be embedded: server authentication required';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 1, 'Binary content cannot be embedded: server authentication required'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Binary content cannot be embedded: server authentication required';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 5, 'Contenu binaire non integrable: authentification serveur requise'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = 'Binary content cannot be embedded: server authentication required';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTR_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION) WHERE SEQ_NAME = 'LTR_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTV_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION_VALUE) WHERE SEQ_NAME = 'LTV_ID';

--changeset sitmun:65-seed-mia-chrome-binary-placeholder-h2 dbms:h2
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM STM_LITERAL_TRANSLATION WHERE LTR_LITERAL = '[binary content]'
INSERT INTO STM_LITERAL_TRANSLATION (LTR_ID, LTR_LITERAL, LTR_LANID)
SELECT COALESCE((SELECT MAX(LTR_ID) FROM STM_LITERAL_TRANSLATION), 0) + 1, '[binary content]', 1
FROM STM_LANGUAGE WHERE LAN_ID = 1;
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 3, '[contingut binari]'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = '[binary content]';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 2, '[contenido binario]'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = '[binary content]';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 1, '[binary content]'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = '[binary content]';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 5, '[contenu binaire]'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = '[binary content]';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTR_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION) WHERE SEQ_NAME = 'LTR_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTV_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION_VALUE) WHERE SEQ_NAME = 'LTV_ID';

--changeset sitmun:65-seed-mia-chrome-binary-placeholder-postgresql dbms:postgresql
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM STM_LITERAL_TRANSLATION WHERE LTR_LITERAL = '[binary content]'
INSERT INTO STM_LITERAL_TRANSLATION (LTR_ID, LTR_LITERAL, LTR_LANID)
SELECT COALESCE((SELECT MAX(LTR_ID) FROM STM_LITERAL_TRANSLATION), 0) + 1, '[binary content]', 1
FROM STM_LANGUAGE WHERE LAN_ID = 1;
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 3, '[contingut binari]'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = '[binary content]';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 2, '[contenido binario]'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = '[binary content]';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 1, '[binary content]'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = '[binary content]';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 5, '[contenu binaire]'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = '[binary content]';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTR_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION) WHERE SEQ_NAME = 'LTR_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTV_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION_VALUE) WHERE SEQ_NAME = 'LTV_ID';

--changeset sitmun:65-seed-mia-chrome-binary-placeholder-oracle dbms:oracle
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM STM_LITERAL_TRANSLATION WHERE LTR_LITERAL = '[binary content]'
INSERT INTO STM_LITERAL_TRANSLATION (LTR_ID, LTR_LITERAL, LTR_LANID)
SELECT COALESCE((SELECT MAX(LTR_ID) FROM STM_LITERAL_TRANSLATION), 0) + 1, '[binary content]', 1
FROM STM_LANGUAGE WHERE LAN_ID = 1;
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 3, '[contingut binari]'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = '[binary content]';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 2, '[contenido binario]'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = '[binary content]';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 1, '[binary content]'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = '[binary content]';
INSERT INTO STM_LITERAL_TRANSLATION_VALUE (LTV_ID, LTV_LTRID, LTV_LANID, LTV_VALUE)
SELECT COALESCE((SELECT MAX(LTV_ID) FROM STM_LITERAL_TRANSLATION_VALUE), 0) + 1, t.LTR_ID, 5, '[contenu binaire]'
FROM STM_LITERAL_TRANSLATION t WHERE t.LTR_LITERAL = '[binary content]';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTR_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION) WHERE SEQ_NAME = 'LTR_ID';
UPDATE STM_SEQUENCE SET SEQ_COUNT = (SELECT COALESCE(MAX(LTV_ID), 0) + 1 FROM STM_LITERAL_TRANSLATION_VALUE) WHERE SEQ_NAME = 'LTV_ID';

